FROM python:3.11-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
# COPY THE NEW FILE INSTEAD
COPY requirements-frontend.txt .
# INSTALL FROM THE NEW FILE INSTEAD
RUN pip install --no-cache-dir -r requirements-frontend.txt
COPY . .
EXPOSE 8501
CMD ["streamlit", "run", "frontend/frontend_app.py", "--server.port=8501", "--server.address=0.0.0.0"]